######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 30 14:37:32 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyTableView.h
SOURCES += main.cpp MyTableView.cpp

RESOURCES +=images.qrc
